Step1 미션 제출합니다
MalibinStudy/GithubProfileApp pull request #1
Opened 2023-02-05 08:46 UTC by Larry7939

[GithubProfileRepositoryTest]

[테스트 케이스]
`입력된 이름에 대한 Github Profile이 반환된다`
`Github Profile을 Local DB에 저장한다`

[개요]
mockk을 활용하여 가짜 GithubProfileRepository 객체를 만들어 해결했습니다.
테스트 대상 메소드인 get,saveGithubProfile이 suspend 메소드인 점을 고려하여 
runBlocking으로 전체를 감싸준 후에 coEvery와 returns메소드로 특정한 값이 나오도록 하였습니다.

[의문점]
GithubProfileRepository 인터페이스만을 mock으로 테스트 하는 것이 맞을까요?
![image](https://user-images.githubusercontent.com/70442964/216809574-68a4e168-0d3e-4733-8415-8952a46c0c29.png)
2주차 미션 가이드에는 class로 적혀있어서, GithubProfileRepository 인터페이스만을 테스트하면 되는 것인지,
GithubProfileRepository 인터페이스를 상속 받은 클래스 DefaultGithubProfileRepository에 대해서도 테스트 해야하는 것인지가 헷갈립니다.

2023-02-08 01:31 UTC, malibinYun requested changes
1단계 미션 고생하셨어요!
mockk를 활용한 테스트를 잘 작성해주셨네요!
어색하고 어려우셨겠지만, 의도에 맞게 미션을 잘 진행해주셨어요 👍👍

제가 미션 가이드를 조금 헷갈리게 적어두었나봅니다 ㅠ_ㅠ
interface에 대한 테스트는 진행하지 않아도 괜찮아요!

피드백 반영하시구 다시 리뷰 요청 부탁드릴게요!

2023-02-08 01:31 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +            )
이 부분은 BeforeEach를 활용해보는 것은 어떨까요?

2023-02-08 01:31 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +                Unit
어느 메서드가 어떤반환을 하는 지 정해주는 것도 given에 속합니다 :)

2023-02-08 01:31 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +            )
기댓 값에 Result.success를 한 번 더 감싸는 것보다, actualResult에서 값을 꺼내서 githubProfile과 비교해보는 것은 어떨까요?

2023-02-08 01:31 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +            )
named Parameter를 활용해보는 것은 어떨까요? :)

2023-02-08 01:31 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +            coVerify(exactly = 1) {
remote가 호출되지 않았는지도 체크해보면 좋겠네요 🙂

2023-02-08 01:31 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/domain/repository/GithubProfileRepositoryTest.kt
> +        runBlocking {
아래 처럼 runBlocking을 구성해도 좋답니다 :)
```suggestion
    fun `입력된 이름에 대한 Github Profile이 반환된다`() = runBlocking {
    
```

2023-02-09 11:15 UTC, Larry7939 commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +            )
> named Parameter를 활용해보는 것은 어떨까요? :)

혹시 named Parameter가 @ParameterizedTest를 의미하는 건가요~?

2023-02-10 06:28 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +            )
정식 명칭으로는 named argument이네요!! 아래 문서를 참고해보세요 :)
https://kotlinlang.org/docs/functions.html#named-arguments

2023-02-13 15:31 UTC, malibinYun approved these changes
미션 고생 많으셨습니다 :)
테스트를 잘 작성해 주셨네요 👍
이 미션으로 repository 테스트가 익숙해지셨으면 좋겠어요 😊

다음 미션 진행해주세요!! 💪

2023-02-13 15:31 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +    fun `setUp`() {
요곤 메서드명이 영어라 백틱을 쓸 필요가 없답니다 :)

2023-02-13 15:31 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +        )
이 부분은 전 BeforeEach로 구현하지 않아요.
각 테스트마다 필요한 값이 다를 수도 있기 때문이에요.
디폴트 값으로 넣어둘 수도 있겠지만, 어디에서는 쓰고, 어디에서는 쓰지 않으면 값이 헷갈릴 수 있기에 잘 활용하지 않게 되더라구요. 🙂

2023-02-13 15:31 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +            )
저는 이렇게 정렬하는 게 더 잘 읽히더라구요 😊
```suggestion
            coEvery { 
                fakeRemoteGithubProfileSource.getGithubProfile("name1")
            } returns Result.success(gitHubProfile)
```

2023-02-13 15:31 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +            )
화이트박스 테스트를 잘 수행해주셨네요! 👍👍

2023-02-13 15:31 UTC, malibinYun commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +        })
요기는 람다 별로 정렬을 해주세요 :)

2023-02-13 15:31 UTC, merged

2023-02-14 00:14 UTC, Larry7939 commented on app/src/test/java/com/malibin/study/github/data/repository/DefaultGithubProfileRepositoryTest.kt
> +    fun `setUp`() {
앗 그렇네요~ ㅎㅎ